### ISSUE TITLE
Block-scoped declarations unsupported outside of strict mode

### ISSUE THREAD

**Issue by RDGthree** [h2non/node-imaginary#11]
Hey there! 

We run ES6 on our server, but let/const/function/class are not yet supported outside of strict mode on our node version (4.4.6, newest available for AWS Elastic Beanstalk). The most recent update broke our build when we updated to it. 

Simple fix should be to add 'use strict'; to the top of the updated ES6 files.

**Comment by RDGthree** [comment]
I'll make a pull request if I have some time today! We love Imaginary, I owe you guys :)

**Comment by h2non** [comment]
I'm sorry to read that, but not quite sure why this is happening to you. 
[TravisCI](https://travis-ci.org/h2non/node-imaginary) is running tests against node.js versions from 0.12.x to latest one.

Babel runtime transpiler should do all the job normalizing the code accordingly.

**Comment by RDGthree** [comment]
Yeah, that seemed bizarre to me as well. I'm digging into it a bit more right now, I'll let you know what I find.

**Comment by h2non** [comment]
Never mind. I think I found the origin of the issue. ES2015 preset plugin for Babel was a dev only dependency. Now it's a runtime one. I'm going to release the fix for this.

Moreover, I don't like the idea of doing magically dark code transpilation at runtime level, so I would probably disable that in the upcoming release. Also, babel dependency is huge, and I think that we, as node.js community, mostly for healthy reasons, should not spend more time installing a bunch of packages in our builds and try to have smaller and light packages.

**Comment by h2non** [comment]
`0.1.11` is now available in `npm` with the fix. 
Would you mind updating your npm tree and verify everything is working?

**Comment by RDGthree** [comment]
Ah, still throwing the same error. Maybe just rip the bandaid now and set up a quick npm script for transpiling? I haven't touched babel's runtime transpilation in a while so I would jump right to a build script. Pure ES5 might be better for NPM anyway. I can make a pull req in a bit if it makes sense.

Completely agreed re: babel. For our node build, we only use the features of ES6 that are available natively to node already so we can avoid transpiling at all. We initially had a runtime transpilation setup and decided to move away from it.

**Comment by h2non** [comment]
I thought about using `npm scripts`, but that would require declaring `babel` as runtime dependency, which is something we don't like.

I removed `babel` dependency at runtime statically releasing `ES5` precompiled code. The issue should be fixed now in `imaginary@0.1.12` release. Try updating your dependency tree.

**Comment by RDGthree** [comment]
Sorry, I just meant using an npm script for building to a static ES5 release. Same result in any case :) Everything works now, thanks!

**Comment by h2non** [comment]
Oh, I see. I thought about that as `npm preinstall` script hook triggered by `npm` as part of the installation pipeline. In any case, I've added it in `Makefile` serving the same purpose.
