### ISSUE TITLE
You published to NPM without building.

### ISSUE THREAD

**Issue by RDGthree** [h2non/node-imaginary#13]
There's no src folder in the node module, and there's no postinstall script. Since this was a patch release, this crashed our production environment.

**Comment by owensbla** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/10188077-121646156_21-s4-v1.png?transparent=1&palette=1&width=246)

**Comment by h2non** [comment]
Oops, sorry about that. It should be fixed in `v0.1.14`, now available on `npm`.

**Comment by RDGthree** [comment]
Thank you!
