### ISSUE TITLE
Memory doesn't get reallocated on docker

### ISSUE THREAD

**Issue by danbachar** [h2non/node-imaginary#16]
hey guys, 
after firing a simple request through the node client to thumbnail a 10 mb image on a docker container that runs imaginary, memory usage never gets reallocated.

my script:
```
for (let i=0; i<20; i++) {
    imaginary('img.jpg')
        .server(serverUrl)
        .thumbnail({ width: 1200 })
        .on('error', (err) => {
          console.error(`resizing image failed because of ${err}`)
    });
}
```

Dockerfile:
```
FROM h2non/imaginary

CMD ["imaginary", "-concurrency" , "1", "-http-cache-ttl", "0"]
```

versions:
imaginary: 1.0.15
bimg: 1.0.18
libvips: 8.6.3"
Docker: 18.06.1-ce

**EDIT:**
added for loop

**Comment by h2non** [comment]
There is another open issue related to this: https://github.com/h2non/imaginary/issues/198

Can you share the image?

**Comment by danbachar** [comment]
thing is, it doesn't replicate when using a bash script: 
```
for i in `seq 1 20`; do
    curl \
        -v \
        -X POST \
        -o output.jpg \
        -H "Content-Type: multipart/form-data" \
        -F "file=@img.jpg" \
        http://localhost:9000/thumbnail\?width\=400\&height\=600
done
```
image is https://upload.wikimedia.org/wikipedia/commons/3/3f/Fronalpstock_big.jpg

**Comment by danbachar** [comment]
> There is another open issue related to this: [h2non/imaginary#198](https://github.com/h2non/imaginary/issues/198)
> 

already commented there :)

**Comment by danbachar** [comment]
after investigating for awhile, we can to a conclusion that this might simply be vips failing with handling heavy simultaneous loads. Also, we switched from using a pipe-stream to buffers, which helped with memory usage as well. Submitting a PR with documentation.
EDIT: PR sent. I've implemented it with promises, but it's only a suggestion; if you know more about streams than I do, please feel free to change it.
