### ISSUE TITLE
Chaining operations

### ISSUE THREAD

**Issue by h2non** [h2non/node-imaginary#4]
``` js
imaginary('image.jpg')
  .chain()
  .crop({ width: 100, height: 100 })
  .rotate(90)
  .on('error', function () { ... })
  .pipe('out.jpg')
```

**Comment by krazyjakee** [comment]
Just a suggestion, but wouldn't it be easier to include the transforms queue in a single object?

Something like...

``` javascript
imaginary('image.jpg')
.params({
  crop: {
    width: 100,
    height: 100
  },
  rotate: 90
})
.on('error', function () { ... })
.pipe('out.jpg')
```

In addition to being a friendlier syntax, the `params` object can easily be manipulated before being passed to node-imaginary. One use case example is that custom transforms can be held in a json file and passed directly to node-imaginary for processing.

**Comment by h2non** [comment]
That would be valid for multiplexed operations over a single request, but you can't do all the operations in a single request.

When multiplexing is not posible, a chainable DSL fits good and it is more expressive, but this also works:

``` js
imaginary('image.jpg')
.operations({
  crop: {
    width: 600,
    height: 400
  },
  extract: {
    top: 90,
    areawidth: 300
  }
})
.on('error', function () { ... })
.pipe('out.jpg')
```

**Comment by krazyjakee** [comment]
Thanks for replying so fast.

Are you saying it works as in that is acceptable? or that it actually works right now?

**Comment by h2non** [comment]
I wanted to say that it would work fine, but that's not supported yet.

**Comment by krazyjakee** [comment]
It looks like a very powerful solution.

When you say multiplexed operations are not possible, is that a limitation (or feature) of Imaginary?
If so, is the workflow that it should create an actual chain of requests to Imaginary for each new operation?

If so, perhaps it should return a promise with the final request passed to it. Do you have any other suggestions for how best to achieve this?

**Comment by h2non** [comment]
It is a small limitation in `imaginary` HTTP API design, but it should be relatively easy to fix.

There's a feature request related to this topic in `imaginary`:
https://github.com/h2non/imaginary/issues/101

Once that is supported, multiple operations can be multiplexed in the same HTTP transaction.
When I initially designed `imaginary` I didn't think that this would be a huge problem since multiple requests for multiple operations should not be a concerning issue in most scenarios, especially in the same cloud infrastructure network, but looks like for most users this can speed up things a bit and I don't see the reason to do not support that. On the other hand, I don't know when I would be able to invest some time working on this since it's a feature I don't need yet. 

For now, the fast solution would be delegating this on the client side, where a programmatic API client can transparently handle this for you performing the required image operations as a pipeline of image transformations, running multiple HTTP requests, if needed, but underlying that logic and complexibility.

**Comment by h2non** [comment]
This is currently supported in latest version via pipeline()

**Comment by h2non** [comment]
Programmatic usage example for reference: https://github.com/h2non/node-imaginary/blob/master/examples/pipeline.js
