### ISSUE TITLE
Passing parameters to request

### ISSUE THREAD

**Issue by krazyjakee** [h2non/node-imaginary#7]
I would like to pass parameters to `request` such as timeout. Is this currently possible? I've had a few tries but can't seem to figure out how to do it.

**Comment by h2non** [comment]
Unfortunately, it is not supported, however, it would be trivial to support. I will accept any PR.

You should be able to pass a raw object with additional `request` options that should be merged with the options internally defined by `imaginary` client.

**Comment by krazyjakee** [comment]
I felt the best place to supply these options was when the imaginary `server` is specified as it keeps those communication options together. You can see an example here: https://github.com/krazyjakee/node-imaginary/blob/master/test/imaginary.js#L43

Those `http_params` are merged here: https://github.com/krazyjakee/node-imaginary/blob/master/lib/request.js#L26-L31

It's also not a breaking change to any existing code.

Please let me know your thoughts on this solution.

**Comment by h2non** [comment]
Feature shipped in `v0.1.10`. Feel free to update your dependency tree.
